language: python
python:
    - "3.6"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y golang gcc

install:
    - pip install pillow pygments
    - python setup.py -q install

script:
    - make

notifications:
    email:
        on_success: change
        on_failure: change
