language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y golang gcc

install:
    - pip install pillow pygments pycodestyle pep257
    - python setup.py -q install

script:
    - make check

notifications:
    email:
        on_success: change
        on_failure: change
