language: python
matrix:
    include:
        - python: 3.4
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y golang gcc

install:
    - pip install pillow pygments pycodestyle pep257
    - python setup.py -q install

script:
    - make check

notifications:
    email:
        on_success: change
        on_failure: change
