language: python
python:
    - "3.6"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y golang gcc
    - sudo pip install pillow pygments

script:
    - make

notifications:
    email:
        on_success: change
        on_failure: change
