build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  # Prepend chosen Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"

test_script:
    - python -m unittest tests/*.py
